service: trackovid19-frontend

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    AWS_EXECUTION_ENV: ${opt:stage, 'dev'}
 
functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY

# Custom Variables
custom:
  stages:
    - dev
    - prd

# Plugins
plugins:
  - serverless-stage-manager
